version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (if any)"

  build:
    commands:
      - echo "Build started"
      - pwd
      - ls -al   # 👈 DEBUG (important)

artifacts:
  files:
    - '**/*'
  discard-paths: no
